main:
  - name: Home
    weight: 100
    url: /
    params:
      icon:
        vendor: fas
        name: house

  - name: Documentation
    url: /docs/
    weight: 300
    params:
      icon:
        vendor: fas
        name: book-open

  - name: Support
    identifier: support
    weight: 400
    url: https://github.com/migliori/power-lite-pdo/issues
    params:
      header: Need Help?
      icon:
        vendor: fas
        name: headset

  - name: GitHub
    parent: support
    url: https://github.com/migliori/power-lite-pdo/issues
    weight: 100
    params:
      icon:
        vendor: fab
        name: github
      description: The code repository.

  - name: Packagist
    parent: support
    url: https://packagist.org/packages/migliori/power-lite-pdo
    weight: 200
    params:
      icon:
        vendor: fas
        name: cube
      description: The package repository.

  - name: Changelog
    parent: support
    url: https://github.com/migliori/power-lite-pdo/blob/main/CHANGELOG.md
    weight: 300
    params:
      icon:
        vendor: fas
        name: clock
      description: What's new?

  - name: Miglisoft
    parent: support
    url: https://www.miglisoft.com/#contact
    weight: 400
    params:
      icon:
        vendor: fas
        name: at
        # className: text-primary
      description: Contact the author
